### ISSUE TITLE
check if status == ENRICHED 

### ISSUE THREAD

**Issue by jthomsen** [linkedtv/editortool#13]
Media resources should probably only be "curatable" if they are in status ENRICHED, also it would be technically possible to curate videos which are in status SERIALLIZED (aka ANNOTATED). So it would be advisable to check the status of media resource in the platform before opening it in the ETvia GET api.linkedtv.eu/mediaresource

Status < 4 (ANNOTATED): Curation not possible, no data in Triple Store
Status = 4: WARNING - Curation possible, but no enrichments yet available
Status = 5: OK
Status = 6: (CURATED) Has been curated

**Comment by lyndonnixon** [comment]
Note that we discuss the idea to make the ENRICHED status a product of using the ET rather than a prerequisite, i.e. after a video is annotated, the next step would be for the editor to select the annotations they want to show in LinkedTV and via the ET they would get and select the enrichments to be associated to each annotation. Once they save from the ET with an enrichment then the video status is updated to ENRICHED.

**Comment by jthomsen** [comment]
ok, so we need to clarify out terms and the workflow then here. 
Until now ENRICHED meant (at least for WP5): "processed through tvenricher and results stored in repository and either ready for manual curation or else for direct unsupervised playout, depending on the scenarios"; "ET data saved" would be status CURATED.
With your comment above, does "via the ET they would get and select the enrichments to be associated to each annotation" mean to invoke the tvenricher service manually via the ET? And if so, is this now the only workflow, i.e. there is no automatic enrichment without editorial curation? Then indeed ENRICHED would be identical to the status CURATED and one of those two we would not need.

**Comment by rtroncy** [comment]
I'm closing this issue since it is clear now that CURATED is different from ANNOTATED or ENRICHED and that curation could take place EITHER after the status ANNOTATED has been reached (for curating the annotations) OR after the status ENRICHED has been reached (for curating the enrichments)

**Comment by jblom** [comment]
+1
