### ISSUE TITLE
RBB Editor Tool: different implementation of acquiring annotations and enrichments?

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/editortool#15]
Do we need to modify the ET for the RBB scenario?
The main set of enrichment links are applied to the news item as a whole (video chapter) not to individual entities.
The chapter entities are now the result of the Named Entity Expansion, not TV2RDF
The chapter enrichments can be determined by a ranking of links according to the set of entities
Will the ET use all three sources of enrichment under consideration: related news items from LinkedTV, related media from the White List and related news articles from the White List?

**Comment by jblom** [comment]
1) If enrichment links are applied to a chapter, rather than an entity or a set of entities (e.g. for a TKK object) this is important for designing the new UI of the ET. 

2) "The chapter entities are now the result of the Named Entity Expansion, not TV2RDF" as long as the chapters are stored in the RDF (and accessible via the API), the programmer of the ET couldn't care less where the chapters came from :)

3) "The chapter enrichments can be determined by a ranking of links according to the set of entities" I don't understand how this relates to having editors select a number of entities as "input query" for the TVEnricher (on demand)

4) "Will the ET use all three sources of enrichment under consideration?" Whatever the TVEnricher returns (or if available any other service that is optimized for certain programmes (TKK, RBB) ). In any case I expect the TVEnricher to be able to return those different kinds of links. Is this the case?

**Comment by rtroncy** [comment]
@jblom TVEnricher can be called "on-demand" using entities labels as input, this is what you do with the editor tool typically in the case of the TKK scenario. TVEnricher is also called by the platform, the input being then a media fragment (more precisely, all annotations attached to a media fragment). The output is already pre-computed and stored in the platform and you could just display it in the editor tool. You can get those pre-computed enrichments either via SPARQL or via the API (e.g. http://api.linkedtv.eu/mediaresource/UUID/enrichment, @jthomsen you confirm?). I think @lyndonnixon is suggesting you to adopt this mode for the RBB use case.

@lyndonnixon The results of the EntityExpansion service are not stored (yet) in the platform.

**Comment by lyndonnixon** [comment]
Would also show entities and enrichments according to "dimensions"
cf. WP2 issue https://github.com/linkedtv/wp2/issues/18

**Comment by rtroncy** [comment]
This might indeed be a handy feature. If there is a need for having new API calls such as http://api.linkedtv.eu/mediaresource/UUID/enrichment/dimension, then, such an issue should be raised on the WP5 repository. We will probably use the [oa:Motivation](http://www.w3.org/ns/oa#d4e555) class for materializing those dimensions, noting that dimensions will just be skos:Concept to be properly defined

**Comment by lyndonnixon** [comment]
For the moment, I am still not clear how @jblom is implementing this.
News item detection for now will not be automatic (open issue at WP1). So the ET will need to allow an editor to tag a chapter as being a News Item, Actually it seems to me this will be the starting point for all the rest. Tagging a chapter as a News Item (probably in the same way as tagging a chapter as an Art Object for TKK) should trigger NamedEntityExpansion to get a set of entities describing the news item (as opposed to individual entities extracted directly from the transcript by Tv2RDF). This set of entities could be shown in the ET as distinct from the Tv2RDF output. When 1+ entities are chosen for suggesting enrichments, the dimensions are significant since one dimension will show results from TVEnricher (White List media) and other dimension(s) from TVNewsEnricher (news articles). The identification of the chapter as a News Item should be saved in the RDF (open issue at LinkedTV Ontology).

**Comment by rtroncy** [comment]
The WP2 EntityExpansion service is described at http://www.linkedtv.eu/wiki/index.php/EntityExpansion. You're suggesting that the EditorTool should call it "on demand". It makes sense to me. Hence, the ET could display the (pre-computed) results of TV2RDF on this program via an api call (or SPARQL query) and display the results of the EntityExpansion service (result is in json).

**Comment by jblom** [comment]
NamedEntityExpansion was integrated a couple of weeks ago. It is called & cached whenever a chapter has been changed. (configured for RBB only). As a results RBB users have additional entities to choose from when searching for enrichments or creating information cards.
