### ISSUE TITLE
Consistent interaction with windows

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/editortool#3]
The windows that appear for the automatic entities could be more like the windows that appear when editing entities in the editor view, i.e. immediately taking focus, being fully visible, closed again with X or ESC.

**Comment by jblom** [comment]
Hi Lyndon, could you please give me a concrete example? . e.g. I have no idea what you mean by "windows that appear for the automatic entities"?

**Comment by lyndonnixon** [comment]
What I mean is when in ET you select an entity in the window of the automatic results, the entity details appears in a window WITHIN the window, often I have to scroll down to see the full window, I can't move it, to close it I click on it again (which IMHO is not very intuitive) etc. On the other hand, in the window showing the editor's selections, if I click on an entity, a window appears which is centred, in focus, over the other windows, moveable, closed by clicking on a X in the top right hand corner etc. I find this type of window much more intuitive to work with so I am suggesting to use the same type of window for the first case. Hope you understand now what I mean :-)

**Comment by jblom** [comment]
Hi Lyndon,

thanks for clarifying. It's clear now ;) I will see what I can do, for V2 I want to make major changes to this view, so it might be a bit of a waste to implement these things now...

**Comment by lyndonnixon** [comment]
Jaap: - When you click on an automatically generated entity you get a popup with the detailed information
