### ISSUE TITLE
Don't generate new UUIDs when not necessary

### ISSUE THREAD

**Issue by rtroncy** [linkedtv/editortool#35]
The  query below displays all chapters, with their titles and who has generated this chapter for the  **_Tussen Kunst - 200 program**_ (Gold Watch by Breguet, Graphic Design Museum episode).

```
SELECT ?mediaFragment ?chapter ?label ?prov
WHERE {
  ?mediaFragment ma:isFragmentOf <http://data.linkedtv.eu/media/8a8187f2-3fc8-cb54-0140-7dd099380002> . 
  ?mediaFragment a ma:MediaFragment .
  ?annotation a oa:Annotation . 
  ?annotation oa:hasTarget ?mediaFragment .
  ?annotation oa:hasBody ?chapter .
  ?annotation prov:wasAttributedTo ?prov .
  ?chapter a linkedtv:Chapter .
  ?chapter rdfs:label ?label .
}
```

The results are [here](http://data.linkedtv.eu/sparql?default-graph-uri=&query=PREFIX+linkedtv%3A+%3Chttp%3A%2F%2Fdata.linkedtv.eu%2Fontologies%2Fcore%23%3E%0D%0APREFIX+ma%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fma-ont%23%3E%0D%0APREFIX+oa%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Foa%23%3E%0D%0APREFIX+prov%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fprov%23%3E%0D%0A%0D%0ASELECT+%3FmediaFragment+%3Fchapter+%3Flabel+%3Fprov%0D%0AWHERE+{%0D%0A++%3FmediaFragment+ma%3AisFragmentOf+%3Chttp%3A%2F%2Fdata.linkedtv.eu%2Fmedia%2F8a8187f2-3fc8-cb54-0140-7dd099380002%3E+.+%0D%0A++%3FmediaFragment+a+ma%3AMediaFragment+.%0D%0A++%3Fannotation+a+oa%3AAnnotation+.+%0D%0A++%3Fannotation+oa%3AhasTarget+%3FmediaFragment+.%0D%0A++%3Fannotation+oa%3AhasBody+%3Fchapter+.%0D%0A++%3Fannotation+prov%3AwasAttributedTo+%3Fprov+.%0D%0A++%3Fchapter+a+linkedtv%3AChapter+.%0D%0A++%3Fchapter+rdfs%3Alabel+%3Flabel+.%0D%0A}%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on)

@jblom You see the problem? You SHOULD NOT generate a new UUID for each media fragment corresponding to a chapter. The idea is that those identifiers are the UUID of the media resource + '#' + temporal start + ',' + temporal end

**Comment by jblom** [comment]
Hi Raphael,

thanks for pointing this out! I have updated my current code.
